eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8762/eureka/

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
