spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KudoAkinichi/flight-config-repo
          default-label: main
          clone-on-start: true
          timeout: 10

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8762/eureka/
  instance:
    prefer-ip-address: true
